# .github/workflows/docker-build.yml
name: Build Docker Image # Workflow name shown on GitHub

# Triggers: Run on push/pull_request to the main branch
on:
  push:
    branches: [ main ] # Adjust if your main branch is named differently (e.g., master)
  pull_request:
    branches: [ main ]

jobs:
  build: # Define a job named 'build'
    runs-on: ubuntu-latest # Run this job on a GitHub-hosted Ubuntu runner

    steps: # Sequence of tasks within the 'build' job
      # 1. Get the code from your repository onto the runner
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx (enhances docker build capabilities in Actions)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build the Docker image using the Dockerfile in your repo
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Directory containing Dockerfile and source code
          file: ./Dockerfile # Path to the Dockerfile
          push: false # IMPORTANT: We are only building, NOT pushing to a registry
          tags: simple-flask-api:ci-build # Tag the image being built (useful for logging)
          load: true # Make the built image available to subsequent steps if needed

      # 4. Optional: Verify the image was built by listing it
      - name: Show Docker images on runner
        run: docker images simple-flask-api:ci-build