# .github/workflows/docker-build.yml

name: Test and Build Docker Image # Renamed workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test: # Renamed job
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your desired Python version

      # ----> NEW STEP: Install Dependencies <----
      # Installs everything from requirements.txt (Flask, Gunicorn, Pytest)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ----> NEW STEP: Run Pytest <----
      # Executes pytest. If tests fail, the workflow stops here.
      - name: Run tests with pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:. # Add current directory to Python's import path
          pytest tests/                 # Now run pytest

      # ---- EXISTING DOCKER STEPS ----
      # Only run if pytest passes above

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false # Still not pushing
          tags: simple-flask-api:ci-build
          load: true

      - name: Show Docker images on runner
        run: docker images simple-flask-api:ci-build